import type { AdCopy, Angle, ComplianceVerdict, LaunchPackage, OfferBrief, Platform } from "@/agents/types";
import { askLLM, type GenerateResult } from "@/lib/llm";

/**
 * Judge / Selector (ZERO_TO_LAUNCH_BUILD_PLAN.md §2 — the Claude Code judge of
 * the Fusion Council mapping, L4). Ranks the angles by launch-worthiness,
 * picks the recommended launch set, assembles the final LaunchPackage, and
 * explains the choice.
 *
 * Design (mirrors the compliance gate's philosophy): the DECISION is
 * deterministic — a transparent score from compliance health + copy
 * completeness + hook diversity — so the ranking is reproducible, works with no
 * model (public URL / seeded run), and honors the S4 rule that a `block`ed
 * angle must sink. The narrative "why" is generated by the model when it's
 * reachable and falls back to a real templated rationale otherwise (never a
 * stub). Both paths are exercised by tests.
 */

export interface AngleScore {
  angleId: string;
  hookType: string;
  headlineSeed: string;
  score: number;
  worstStatus: ComplianceVerdict["status"];
  breakdown: { compliance: number; completeness: number; platforms: number };
  reason: string; // short deterministic explanation of THIS angle's score
}

export interface JudgeResult {
  ranking: AngleScore[]; // every angle, best first
  launchPackage: LaunchPackage;
  rationale: string;
  rationaleSource: "model" | "heuristic";
}

const DEFAULT_LAUNCH_SET_SIZE = 3;

const STATUS_RANK = { pass: 0, flag: 1, block: 2 } as const;
function worseStatus(a: ComplianceVerdict["status"], b: ComplianceVerdict["status"]): ComplianceVerdict["status"] {
  return STATUS_RANK[b] > STATUS_RANK[a] ? b : a;
}

/** Compliance contribution: reward clean copy, punish flags, sink blocks. */
function complianceScore(status: ComplianceVerdict["status"]): number {
  return status === "pass" ? 2 : status === "flag" ? -1 : -6;
}

/** An ad is "complete" when its core fields are present. */
function isComplete(c: AdCopy): boolean {
  return !!(c.headline.trim() && c.primaryText.trim() && c.cta.trim());
}

/** Score one angle from its copy + verdicts. Pure + exported for tests. */
export function scoreAngle(
  angle: Angle,
  copies: AdCopy[],
  verdicts: ComplianceVerdict[],
): AngleScore {
  const mine = copies.filter((c) => c.angleId === angle.id);
  const myVerdicts = verdicts.filter((v) => v.angleId === angle.id);

  let compliance = 0;
  let worstStatus: ComplianceVerdict["status"] = "pass";
  for (const v of myVerdicts) {
    compliance += complianceScore(v.status);
    worstStatus = worseStatus(worstStatus, v.status);
  }
  // No verdicts at all (compliance not run) is neutral, not a bonus.
  if (myVerdicts.length === 0) worstStatus = "pass";

  const completeness = mine.filter(isComplete).length; // +1 per complete ad
  const platforms = new Set(mine.map((c) => c.platform)).size; // reach across platforms

  const score = compliance + completeness + platforms;

  const reason =
    worstStatus === "block"
      ? "Has BLOCK-level copy — not launch-ready until fixed."
      : worstStatus === "flag"
        ? "Compliant with fixes; solid once flags are addressed."
        : mine.length === 0
          ? "No copy generated yet."
          : "Clean across platforms — launch-ready.";

  return {
    angleId: angle.id,
    hookType: angle.hookType,
    headlineSeed: angle.headlineSeed,
    score,
    worstStatus,
    breakdown: { compliance, completeness, platforms },
    reason,
  };
}

/** Rank all angles best-first (score desc, then clean-before-flagged, stable). */
export function rankAngles(angles: Angle[], copies: AdCopy[], verdicts: ComplianceVerdict[]): AngleScore[] {
  return angles
    .map((a) => scoreAngle(a, copies, verdicts))
    .map((s, i) => ({ s, i }))
    .sort((x, y) =>
      y.s.score - x.s.score ||
      STATUS_RANK[x.s.worstStatus] - STATUS_RANK[y.s.worstStatus] ||
      x.i - y.i,
    )
    .map(({ s }) => s);
}

/** Pick the launch set: top-N by score, but never recommend a BLOCK-level angle
 *  unless there is literally nothing cleaner. */
export function selectLaunchSet(ranked: AngleScore[], angles: Angle[], n = DEFAULT_LAUNCH_SET_SIZE): Angle[] {
  const byId = new Map(angles.map((a) => [a.id, a]));
  const launchable = ranked.filter((s) => s.worstStatus !== "block");
  const pool = launchable.length > 0 ? launchable : ranked;
  return pool.slice(0, n).map((s) => byId.get(s.angleId)).filter((a): a is Angle => !!a);
}

/** Build the day-1 launch checklist (build plan §1.5). Templated + a few
 *  dynamic inserts driven by the offer's risk profile and the gate's findings. */
export function buildChecklist(
  brief: OfferBrief,
  verdicts: ComplianceVerdict[],
  recommendedAngles: Angle[],
  platforms: Platform[],
): string[] {
  const items: string[] = [];
  const hasBlock = verdicts.some((v) => v.status === "block");
  const hasFlag = verdicts.some((v) => v.status === "flag");
  const platformLabel = platforms.length ? platforms.map((p) => p.toUpperCase()).join(" + ") : "your platforms";

  if (hasBlock) {
    items.push("⚠ Resolve every BLOCK-flagged ad before launch — this offer's claims draw heavy ad-policy review, and a block will get the ad (or account) actioned.");
  }
  items.push(`Install and verify your tracking pixel/conversion tag for ${platformLabel}; fire one test conversion before spending a dollar.`);
  items.push("Point every ad at the advertorial pre-lander (not the raw offer) and confirm the FTC disclosure renders above the fold.");
  if (hasFlag) {
    items.push("Apply the compliance gate's suggested fixes to any FLAG-level copy (add 'results not typical', drop absolute guarantees, etc.) before scaling.");
  }
  items.push(`Launch the ${recommendedAngles.length} recommended angle(s) as separate ad sets at a small equal daily budget; let each exit the learning phase before judging it.`);
  items.push("Day 1: watch CTR and CPC per angle; pause any angle well below the account average once it has ~1,000 impressions with no clicks.");
  items.push("Day 2-3: shift budget toward the angle(s) with the lowest cost per lead; refresh the creative on fatiguing winners before CTR decays.");
  if (brief.complianceRisk === "high") {
    items.push("Keep substantiation on file for every health/benefit claim — high-risk verticals get manual review and require proof on request.");
  }
  return items;
}

/** Deterministic rationale — the always-available fallback (and it's genuinely
 *  informative, not a placeholder). */
export function heuristicRationale(ranked: AngleScore[], launchSet: Angle[]): string {
  if (launchSet.length === 0) return "No launch-ready angles were found — generate copy and re-run the gate first.";
  const picks = launchSet
    .map((a) => {
      const s = ranked.find((r) => r.angleId === a.id);
      const health = s?.worstStatus === "pass" ? "clean across platforms" : s?.worstStatus === "flag" ? "compliant once its flags are fixed" : "the least-risky option available";
      return `“${a.headlineSeed}” (${a.hookType}, ${health})`;
    })
    .join("; ");
  const blocked = ranked.filter((r) => r.worstStatus === "block").length;
  const tail = blocked ? ` ${blocked} angle(s) were held back for BLOCK-level policy violations.` : "";
  return `Recommended launch set, ranked by compliance health, cross-platform copy completeness, and hook diversity: ${picks}.${tail} These lead because they pair a distinct psychological hook with copy the gate can clear.`;
}

/** Optional model-written narrative; falls back to heuristicRationale on any error. */
async function modelRationale(
  brief: OfferBrief,
  ranked: AngleScore[],
  launchSet: Angle[],
): Promise<{ text: string; source: "model" | "heuristic" }> {
  const fallback = heuristicRationale(ranked, launchSet);
  if (launchSet.length === 0) return { text: fallback, source: "heuristic" };
  try {
    const summary = ranked
      .map((r) => `- ${r.headlineSeed} [${r.hookType}] score=${r.score} status=${r.worstStatus}`)
      .join("\n");
    const picks = launchSet.map((a) => a.headlineSeed).join(" | ");
    const res = await askLLM(
      [
        {
          role: "system",
          content:
            "You are the launch strategist for a media-buying team. In 2-4 sentences, explain WHY the recommended angles were chosen over the rest. Be specific about compliance health and hook diversity. Plain prose only — no lists, no preamble, no markdown.",
        },
        {
          role: "user",
          content: `Offer: ${brief.product} (${brief.vertical}). Ranked angles:\n${summary}\n\nRecommended launch set: ${picks}\n\nWrite the rationale.`,
        },
      ],
      { temperature: 0.5, maxTokens: 1200 },
    );
    const text = res.text.trim();
    return text.length > 20 ? { text, source: "model" } : { text: fallback, source: "heuristic" };
  } catch {
    return { text: fallback, source: "heuristic" };
  }
}

export interface JudgeInput {
  brief: OfferBrief;
  angles: Angle[];
  copy: AdCopy[];
  verdicts: ComplianceVerdict[];
  advertorialUrl: string;
  launchSetSize?: number;
}

export interface JudgeOutput {
  result: JudgeResult;
  meta: GenerateResult | null;
}

/** Run the Judge: rank, select, assemble the LaunchPackage, explain. */
export async function judge(input: JudgeInput): Promise<JudgeOutput> {
  const { brief, angles, copy, verdicts, advertorialUrl } = input;
  const ranking = rankAngles(angles, copy, verdicts);
  const recommendedAngles = selectLaunchSet(ranking, angles, input.launchSetSize ?? DEFAULT_LAUNCH_SET_SIZE);
  const recommendedIds = new Set(recommendedAngles.map((a) => a.id));
  const recommendedCopy = copy.filter((c) => recommendedIds.has(c.angleId));
  const platforms = [...new Set(recommendedCopy.map((c) => c.platform))];

  const { text: rationale, source } = await modelRationale(brief, ranking, recommendedAngles);

  const launchPackage: LaunchPackage = {
    offerBrief: brief,
    recommendedAngles,
    copy: recommendedCopy,
    advertorialUrl,
    checklist: buildChecklist(brief, verdicts, recommendedAngles, platforms),
  };

  return {
    result: { ranking, launchPackage, rationale, rationaleSource: source },
    // meta is null here because the rationale path may be heuristic; the model
    // call (if any) isn't the product artifact, the ranking is.
    meta: null,
  };
}
